spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://192.168.180.128:2181
  consumer:
    check: false
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 192.168.180.128:22122
